#Importing Packages

In [ ]:
import numpy as np
import pandas as pd
import plotly
import plotly.figure_factory as ff
import plotly.graph_objs as go
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

#Reading data

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
#mount gdrive for reading data

In [ ]:
data = pd.read_csv('/content/gdrive/My Drive/Datasets/task_b.csv')
data=data.iloc[:,1:]

In [ ]:
data.head()

f1            f2        f3    y
0  -195.871045 -14843.084171  5.532140  1.0
1 -1217.183964  -4068.124621  4.416082  1.0
2     9.138451   4413.412028  0.425317  0.0
3   363.824242  15474.760647  1.094119  0.0
4  -768.812047  -7963.932192  1.870536  0.0

In [ ]:
#looking at the correlation between the dependent and independent variables
data.corr()['y']   

f1    0.067172
f2   -0.017944
f3    0.839060
y     1.000000
Name: y, dtype: float64

In [ ]:
#find the std deviation of each variable
data.std()

f1      488.195035
f2    10403.417325
f3        2.926662
y         0.501255
dtype: float64

In [ ]:
X=data[['f1','f2','f3']].values
Y=data['y'].values
print(X.shape)
print(Y.shape)

(200, 3)
(200,)


# What if our features are with different variance 

<pre>
* <b>As part of this task you will observe how linear models work in case of data having feautres with different variance</b>
* <b>from the output of the above cells you can observe that var(F2)>>var(F1)>>Var(F3)</b>

> <b>Task1</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' and check the feature importance

> <b>Task2</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance

</pre>

<h3><font color='blue'> Make sure you write the observations for each task, why a particular feautre got more importance than others</font></h3>

In [ ]:
https://stackoverflow.com/questions/34052115/how-to-find-the-importance-of-the-features-for-a-logistic-regression-model

#SVM without Standardization

In [ ]:
model = SGDClassifier(loss='hinge')
model.fit(X,Y)
# get importance
print(model.coef_)
importance = model.coef_[0]
# summarize feature importance
for i,v in enumerate(importance):
	print(f'Feature: {i}, Score: {v}')
 


[[10039.273864    1575.76305879 11101.68891116]]
Feature: 0, Score: 10039.273864003137
Feature: 1, Score: 1575.7630587905896
Feature: 2, Score: 11101.688911164554


https://machinelearningmastery.com/calculate-feature-importance-with-python/

#Logistic model without Standardization

In [ ]:
model = SGDClassifier(loss='log')
model.fit(X,Y)
# get importance
print(model.coef_)
importance = model.coef_[0]
# summarize feature importance
for i,v in enumerate(importance):
	print(f'Feature: {i}, Score: {v}')


[[18064.29183193 15945.29640536  9857.73757072]]
Feature: 0, Score: 18064.291831928815
Feature: 1, Score: 15945.29640536033
Feature: 2, Score: 9857.737570724426


#Standardization

In [ ]:
st = StandardScaler()
X = st.fit_transform(X)

#SVM + Standardization

In [ ]:
model = SGDClassifier(loss='hinge')
model.fit(X,Y)
# get importance
print(model.coef_)
importance = model.coef_[0]
# summarize feature importance
for i,v in enumerate(importance):
	print('Feature: %0d, Score: %.5f' % (i,v))

[[-1.60463973 -0.28486454 12.58339637]]
Feature: 0, Score: -1.60464
Feature: 1, Score: -0.28486
Feature: 2, Score: 12.58340


#Logistic Regression + Standardization

In [ ]:
model = SGDClassifier(loss='log')
model.fit(X,Y)
# get importance
print(model.coef_)
importance = model.coef_[0]
# summarize feature importance
for i,v in enumerate(importance):
	print('Feature: %0d, Score: %.5f' % (i,v))

[[-1.0330077   0.91698577 12.06974254]]
Feature: 0, Score: -1.03301
Feature: 1, Score: 0.91699
Feature: 2, Score: 12.06974


https://towardsdatascience.com/effect-of-feature-standardization-on-linear-support-vector-machines-13213765b812




*   Without standardization, it can be seen that the coefficients are so large and hence will overfit the data and giving higg importance to features 
*   With standardization, the coefficients are reduced drastically, although the feature importance are retained to some extent and since they're not too large, the model avoids overfitting the data.


*   Refered the link above for better explanation.




